name: build
on:
  pull_request:
    branches:
      - main
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
      - name: run make build
        run: make build
      - name: make build installer
        run: make build-installer
      - name: run build multifile installer
        run: make build-multifile-installer
      - name: Generate operator helm charts
        run: make build-helm-installer
      - name: Generate operator helm document
        run: make generate-helm-docs
      - name: Check for uncommitted changes
        run: make check-all-committed
      - name: Show the uncommitted "git diff"
        if: ${{ failure() }}
        run: git diff ; false
