name: image-publisher

on:
  workflow_dispatch:
    inputs:
      REGISTRY_NAMESPACE:
        required: true
        default: ocs-dev
      IMAGE_TAG:
        required: false
        default: ""
      BUNDLE_VERSION:
        required: false
        default: ""

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and push docker images
      env:
        IMAGE_NAME: cephcsi-operator
        REGISTRY_NAMESPACE: ${{ github.event.inputs.REGISTRY_NAMESPACE }}
        IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
        IMAGE_TAG_SHA: ${{ github.ref_name }}-${{ github.sha }}
        BUNDLE_VER: ${{ github.event.inputs.BUNDLE_VERSION }}
      run: |
        # Set IMAGE_TAG to a calculated <branch>-<sha> if not specified
        export IMAGE_TAG=${IMAGE_TAG:-${IMAGE_TAG_SHA:0:-33}}
        # Export BUNDLE_VERSION if specified else use the one in makefile
        [ -n "$BUNDLE_VER" ] && export BUNDLE_VERSION=${BUNDLE_VER}
        make -f Makefile.Downstream.mk docker-build docker-push
        make -f Makefile.Downstream.mk bundle-build bundle-push
