name: Unit Tests
on:
  pull_request:
    paths-ignore:
      - 'vendor/*'
    branches:
      - main
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
    unittests:
      name: unittests
      runs-on: ubuntu-latest
      steps:
        - name: checkout     
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            fetch-depth: 1
        - name: setup go    
          uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
          with: 
            go-version-file: go.mod
            check-latest: true
        - name:  run unit tests
          run:   make test
